export const MOD_BASISWERT = 'MOD_BASISWERT';

export const APPSTORE_BASISWERT_CHANGED = 'APPSTORE_BASISWERT_CHANGED';
export const APPSTORE_CHANGED = 'APPSTORE_CHANGED';
export const SOMETHING = "DERP";