export const MOD_BASISWERT = 'MOD_BASISWERT';
export const MOD_KREDITWERT = 'MOD_KREDITWERT';

export const APPSTORE_BASISWERT_CHANGED = 'APPSTORE_BASISWERT_CHANGED';
export const APPSTORE_CHANGED = 'APPSTORE_CHANGED';
export const MOD_CHILDREN = "MOD_CHILDREN";
export const MOD_CHILDREN_AGE = "MOD_CHILDREN_AGE";
