export const INPUT_MONAT_NETTO = 'INPUT_MONAT_NETTO';
export const INPUT_MONAT_AUSGABEN = 'INPUT_MONAT_AUSGABEN';
export const INPUT_FREI_VERFUEGBAR_PERCENT = 'INPUT_FREI_VERFUEGBAR_PERCENT';
export const INPUT_FREI_VERFUEGBAR_ABS = 'INPUT_FREI_VERFUEGBAR_ABS';